version: "2.1"

services:
  db:
    image: mysql:8.0
    container_name: db
    tty: true
    ports:
      - "3306:3306"
    command:  --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    environment:
      MYSQL_DATABASE: pizzaShop
      MYSQL_USER: pizzaShop
      MYSQL_PASSWORD: pizzaShop@123
      MYSQL_ROOT_PASSWORD: pizzaShop@123
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: pizza-shop:backend
    container_name: backend
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./backend:/var/www/html/
    ports:
      - "9000:9000"
    networks:
      - app-network

  webserver:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    image: pizza-shop:webserver
    container_name: webserver
    ports:
      - "3000:3000"
    depends_on:
      - backend
    links:
      - db
    volumes:
      - ./backend:/var/www/html/
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: pizza-shop:frontend
    container_name: frontend
    depends_on:
      - webserver
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local